import type { DashboardData } from "../types";

const API_BASE = import.meta.env.VITE_FPL_API_URL || (import.meta.env.DEV ? "/fpl-api" : "./data");

export class FplApiError extends Error {}

async function request<T>(path: string): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`);
  if (!response.ok) throw new FplApiError(`FPL request failed: ${response.status} ${path}`);
  return response.json() as Promise<T>;
}

export interface BootstrapEvent {
  id: number;
  name: string;
  deadline_time: string;
  finished: boolean;
  is_current: boolean;
  is_next: boolean;
}

interface Bootstrap { events: BootstrapEvent[]; }
interface LeagueStanding { entry: number; rank: number; last_rank: number; entry_name: string; player_name: string; total: number; }
interface LeagueResponse { league: { name: string }; standings: { results: LeagueStanding[] }; }

export async function inspectCurrentSeason(): Promise<{ event: BootstrapEvent; league?: LeagueResponse }> {
  const bootstrap = await request<Bootstrap>("/bootstrap-static");
  const event = bootstrap.events.find((item) => item.is_current) ?? bootstrap.events.find((item) => item.is_next) ?? bootstrap.events[0];
  if (!event) throw new FplApiError("The FPL season has no events");
  const leagueId = import.meta.env.VITE_FPL_LEAGUE_ID;
  if (!leagueId) return { event };
  const league = await request<LeagueResponse>(API_BASE.includes("/api") ? "/league" : `/leagues-classic/${leagueId}/standings/?page_standings=1`);
  return { event, league };
}

// A static Pages deployment reads normalized snapshots generated by the future backend.
export async function loadPublishedSnapshot(): Promise<DashboardData> {
  return request<DashboardData>("/dashboard.json");
}
